### ISSUE TITLE
Object.entries() 함수 인식 문제

### ISSUE THREAD

**Issue by djkeh** [rhiokim/flybook#1]
* 사용환경: Windows 7, `Git CMD`
  * node 버젼: 6.10.0
  * npm 버젼: 3.10.10
  * yarn 버젼: 0.24.5
  * 설치 패키지: yarn, react, react-dom(, [object.entries](https://www.npmjs.com/package/object.entries) - 해결을 위해 시도해봄)
* 증상: `flybook docs` 명령어를 실행할 경우 `Object.entries is not a function` TypeError 발생
* 소스코드 지점: `flybook/components/layout.js`, [26번째 줄](https://github.com/rhiokim/flybook/blob/master/components/layout.js#L26)
* 재현
  1. `yarn init`
  2. `yarn add flybook -D`
  3. `./package.json` 파일에 `"scripts"` 커맨드 추가: `"docs": "flybook docs --outdir=out"`
  4. `yarn docs`
* 로그

```
C:\test>
C:\test>npm --version
3.10.10

C:\test>yarn --version
0.24.5

C:\test>type package.json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "docs": "flybook docs --outdir=out"
  },
  "devDependencies": {
    "flybook": "^1.0.7"
  }
}

C:\test>yarn docs
yarn docs v0.24.5
$ flybook docs --outdir=out
C:\test\node_modules\flybook\dist\components\layout.js:58
            Object.entries(toc[key]).map(function (item, i) {
                   ^

TypeError: Object.entries is not a function
    at C:\test\node_modules\flybook\dist\components\layout.js:58:20
    at Array.map (native)
    at module.exports (C:\test\node_modules\flybook\dist\components\layout.js:54:26)
    at C:\test\node_modules\react-dom\lib\ReactCompositeComponent.js:306:16
    at measureLifeCyclePerf (C:\test\node_modules\react-dom\lib\ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (C:\test\node_modules\react-dom\lib\ReactCompositeComponent.js:305:14)
    at ReactCompositeComponentWrapper._constructComponent (C:\test\node_modules\react-dom\lib\ReactCompositeComponent.js:280:21)
    at ReactCompositeComponentWrapper.mountComponent (C:\test\node_modules\react-dom\lib\ReactCompositeComponent.js:188:21)
    at Object.mountComponent (C:\test\node_modules\react-dom\lib\ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (C:\test\node_modules\react-dom\lib\ReactCompositeComponent.js:371:34)
error Command failed with exit code 1.

C:\test>
```

위 이슈 확인 부탁드립니다.
감사합니다~

**Comment by Rokt33r** [comment]
Node.js 버젼 문제인 듯 하네여
@rhiokim Object.entries 폴리필이 필요할듯 합니다 흐흐

**Comment by gimdongwoo** [comment]
http://node.green/#ES2017-features-Object-static-methods-Object-entries
6.11.0부터 지원되는 것으로 보이니, 폴리필이 필요해 보여요.

**Comment by rhiokim** [comment]
@Rokt33r @gimdongwoo 👍 
감사합니다. 하위 호환성 문제 확인하고 수정했습니다.

**Comment by rhiokim** [comment]
But `flybook` has a few of issues on window system. It'll be fixed soon
